### ISSUE TITLE
Failed to visulize point cloud.

### ISSUE THREAD

**Issue by Daoming-Chen** [stm32f303ret6/livox_laser_simulation_RO2#2]
I put this ros package into my workspace, then I add the livox mid360 to my robot.xacro like this:

```xml
<!-- livox mid 360 -->
<gazebo reference="livox_mid360_1">
  <sensor type="ray" name="livox_mid360">
    <pose>0 0 0 0 0 0</pose>
    <visualize>true</visualize>
    <update_rate>10</update_rate>
    <plugin name="livox_mid360_plugin" filename="libros2_livox.so">
      <ray>
        <scan>
          <horizontal>
            <samples>100</samples>
            <resolution>1</resolution>
            <min_angle>${0}</min_angle>
            <max_angle>${2*M_PI}</max_angle>
          </horizontal>
          <vertical>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>${-7.22/180*M_PI}</min_angle>
            <max_angle>${55.22/180*M_PI}</max_angle>
          </vertical>
        </scan>
        <range>
          <min>0.1</min>
          <max>200.0</max>
          <resolution>0.002</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <visualize>true</visualize>
      <samples>24000</samples>
      <downsample>1</downsample>
      <csv_file_name>$(find ros2_livox_simulation)/scan_mode/mid360.csv</csv_file_name>
      <topic>livox_mid360</topic>
    </plugin>
  </sensor>
</gazebo>
```

Then I try to open gazebo sim:

![Screenshot from 2023-06-19 10-53-14](https://github.com/stm32f303ret6/livox_laser_simulation_RO2/assets/69784031/f570c18f-4b9a-4f93-ab99-041e6e5a8647)

and I got this when I use `ros2 topic echo /livox_mid360 --no-arr`

```
---
header:
  stamp:
    sec: 150
    nanosec: 750000000
  frame_id: livox_mid360
height: 1
width: 5673
fields: '<sequence type: sensor_msgs/msg/PointField, length: 3>'
is_bigendian: false
point_step: 12
row_step: 68076
data: '<sequence type: uint8, length: 68076>'
is_dense: false
---
header:
  stamp:
    sec: 150
    nanosec: 814000000
  frame_id: livox_mid360
height: 1
width: 6500
fields: '<sequence type: sensor_msgs/msg/PointField, length: 3>'
is_bigendian: false
point_step: 12
row_step: 78000
data: '<sequence type: uint8, length: 78000>'
is_dense: false
---
```

When I try to visulize the point could in rviz2, no point cloud there:

![Screenshot from 2023-06-19 10-58-43](https://github.com/stm32f303ret6/livox_laser_simulation_RO2/assets/69784031/4009a656-cb4a-4ba1-8496-334f35fcd232)

instead, I got this error message: 

```
[rviz2-3] [INFO] [1687143526.837245203] [rviz2]: Message Filter dropping message: frame 'livox_mid360' at time 258.949 for reason 'Unknown'
[rviz2-3] [INFO] [1687143526.965323983] [rviz2]: Message Filter dropping message: frame 'livox_mid360' at time 259.010 for reason 'Unknown'
[rviz2-3] [INFO] [1687143527.093077326] [rviz2]: Message Filter dropping message: frame 'livox_mid360' at time 259.074 for reason 'Unknown'
[rviz2-3] [INFO] [1687143527.317656920] [rviz2]: Message Filter dropping message: frame 'livox_mid360' at time 259.250 for reason 'Unknown'
[rviz2-3] [INFO] [1687143527.445013446] [rviz2]: Message Filter dropping message: frame 'livox_mid360' at time 259.314 for reason 'Unknown'
[rviz2-3] [INFO] [1687143527.605317809] [rviz2]: Message Filter dropping message: frame 'livox_mid360' at time 259.379 for reason 'Unknown'
[rviz2-3] [INFO] [1687143527.733095200] [rviz2]: Message Filter dropping message: frame 'livox_mid360' at time 259.544 for reason 'Unknown'
[rviz2-3] [INFO] [1687143527.861112040] [rviz2]: Message Filter dropping message: frame 'livox_mid360' at time 259.609 for reason 'Unknown'
[rviz2-3] [INFO] [1687143527.989132449] [rviz2]: Message Filter dropping message: frame 'livox_mid360' at time 259.671 for reason 'Unknown'
[rviz2-3] [INFO] [1687143528.149605975] [rviz2]: Message Filter dropping message: frame 'livox_mid360' at time 259.850 for reason 'Unknown'
```

Does any one have some idea of how to solve this?
